### PR TITLE
User notifications

### PR DESCRIPTION
**Pull request by iamlasse**
New notifications feature.

### CODE REVIEW

**Comment by jeffshaver** [comment]
If you click on the notifications icon, the url is switched to `#!` which it shouldn't. No need to change url

**Comment by iamlasse** [comment]
Good point, the href needs something it seems to go to link is there a better way?

**Comment by iamlasse** [comment]
Maybe do without a link... Maybe just click on element?

**Comment by trustieee** [comment]
Can just change cursor on hover, and do a click event.

**Comment by trustieee** [comment]
Looks good. Only needs a merger from master before being ready. It's currently set to override some changes I made earlier today.

**Comment by iamlasse** [comment]
I pulled in and merged latest master at the time of push

**Pull request merged**
