### PR TITLE
Upload picture

### PR DESCRIPTION
**Pull request by Sandersd**
Added cfs:standard-packages and cfs:gridfs for CollectionFS
Added Edit button (needs styling/better placement) that when pressed, hides and shows:
File input (Choose File button and file name) and an Upload button.
User selects file and the file begins uploading to the server, then when the users hits Upload, their profile.avatarImg is updated with the file.

### CODE REVIEW

**Comment by iamlasse** [comment]
Needs a little more styling work, I can help if you'd like

**Comment by Sandersd** [comment]
Ya I don't actually know sass so some help would be much appreciated haha. Does it still show broken image after refresh? I was thinking of using {{url}} from CollectionFS but I didn't want to mess with the user db too much

**Comment by Sandersd** [comment]
but if it doesn't work, I probably should..

**Comment by iamlasse** [comment]
on refresh it updates, but not directly on change. Let me know I'll pull your branch and add a little sass

**Comment by iamlasse** [comment]
yeah put the function in a helper file, and return this.url

**Comment by Sandersd** [comment]
Which function, the Images.insert?

**Comment by iamlasse** [comment]
Yeah the avatarImg

**Comment by trustieee** [comment]
I left some comments on slack for @Sandersd to go over some remaining styling with @iamlasse .

**Pull request closed without merging**
